### DISCUSSION TITLE
Support for inserting new lines?

### DISCUSSION THREAD

**Discussion by Bartlomiejsz** [Siilwyn/css-declaration-sorter#182] [Ideas]
Hi!
I'm wondering, if there are any plans to allow reorder function to insert empty line between some styles group?

Best regards

**Comment by Siilwyn** [comment]
:wave: hey sorry for the late reply, I don't have any plans for this. Do you think this would be useful? Most selectors I write have a handful of properties so there would be a lot of newlines which doesn't aid readability.

**Comment by Bartlomiejsz** [comment]
Hi @Siilwyn, thank you for answer.
Yes, I guess so, whole point of ordering styles in some way is to make it more readable, and I believe splitting those to some particular groups makes it even better.
I was trying to achieve https://css-tricks.com/poll-results-how-do-you-order-your-css-properties/ specifically

**Comment by Siilwyn** [comment]
Hey sorry for not responding, I'm not sure what to do with this issue yet. I don't agree since it can decrease readability for selectors that have only one or two selectors in each group. However if more people feel like this should be an option it might be worth considering, it does add significant complexity to the code that's why I'm hesitant.

*Edit*: I moved this to a feature idea/request so people can vote.

**Comment by azabraao** [comment]
That would be great! 
If you take the concentric-css as an example, it comes with spaces in between style groups:

```css
#Concentric-CSS-Overview {
  display: ;    /* Directions about where and how the box is placed */
  position: ;
  float: ;
  clear: ;

  visibility: ; /* Next: can the box be seen? */
  opacity: ;
  z-index: ;

  margin: ;     /* Layers of the box model, from outside to inside */
  outline: ;
  border: ;
  background: ; /* (padding and content BOTH get the background color) */
  padding: ;

  width: ;      /* Content dimensions and scrollbars */
  height: ;
  overflow: ;

  color: ;      /* Textual content */
  text: ;
  font: ;
}

```

(from https://github.com/brandon-rhodes/Concentric-CSS/blob/master/style.css)
