### ISSUE TITLE
css-declaration-sorter breaks some border rules

### ISSUE THREAD

**Issue by ludofischer** [Siilwyn/css-declaration-sorter#157]
Even with `keepOverrides: true`, css-declaration-sorter sometimes changes border styles.
Take this example.

```css
a
{
  border-top: 1px solid;
  border-color: purple;
}
```
Even with `keepOverrides: true`, css-declaration-sorter turns it into:

```css
a
{
  border-color: purple;
  border-top: 1px solid;
}
```
In the original CSS, the top border was purple, now it's not. This happens because the sorting does not take into account that  some declarations override others even if they are not shorthand for each other. Originally reported as https://github.com/cssnano/cssnano/issues/1054
