### ISSUE TITLE
Is there a way to sort declarations before nestings?

### ISSUE THREAD

**Issue by misund** [Siilwyn/css-declaration-sorter#23]
It would be nice to have a config parameter to output declarations before nestings.

### Example
Before:
```scss
.foo {
  .bar {
    display: block;
  }

  display: block;
}
```

After:
```scss
.foo {
  display: block;

  .bar {
    display: block;
  }
}
```
