### ISSUE TITLE
Logical border width properties don't retain override order

### ISSUE THREAD

**Issue by AndrewLeedham** [Siilwyn/css-declaration-sorter#262]
I seem to have run in to a bug via cssnano, which I have traced back to here. I have logical border width properties overriding a reset of the border width, but the order of the override is not being retained. So given:
```css
div {
    background: grey;
    border-width: 0;
    border-top-width: 1px;
    border-inline-start-width: 1px;
 }
```
I am getting:
```css
div {
    background: grey;
    border-inline-start-width: 1px;
    border-width: 0;
    border-top-width: 1px;
}
```
This means the `border-inline-start-width` is ignored because the `border-width` overrides it.

I created a minimal repro with the above code to demonstrate the issue: https://runkit.com/embed/zdr51an9amcj.
