### ISSUE TITLE
`keepOverrides` failing to preserve ordering of border style declarations

### ISSUE THREAD

**Issue by jvnlwn** [Siilwyn/css-declaration-sorter#270]
### Description
Unexpected reordering of border style declarations are breaking certain styles.

### Example
`cssDeclarationSorter` will take this CSS:
```css
.border-test {
  border-width: 0;
  border-radius: 0;
  border-bottom: 1px;
}
```
And turn it into:
```css
.border-test {
  border-bottom: 1px;
  border-radius: 0;
  border-width: 0;
}
```

This may be expected, but what is not expected is if you pass `{ keepOverrides: true }`. You get the same result.

Here is a [repo/branch](https://github.com/jvnlwn/css-declaration-sorter/tree/test/border) proving the issue. Checkout the fix/border branch and run `npm test` to see the failing test.

### Expected behavior:
Passing `{ keepOverrides: true }` would retain the style declaration ordering.

### Workaround:
My current workaround is to provide `cssDeclarationSorter` with the option:
```javascript
{
  order: ()=> 0 // preseve style declaration ordering
}
```

This is necessary for me in a craco project which depends on cssnano which uses this repo, which passes the `{ keepOverrides: true }` by default.

Thanks!
