### ISSUE TITLE
Sorting new animation properties has side effects 

### ISSUE THREAD

**Issue by johannesodland** [Siilwyn/css-declaration-sorter#338]
Sorting new animation properties has side effects (https://github.com/cssnano/cssnano/issues/1514)

Input: 

```css
@keyframes test {
  to {
    opacity: 1;
  }
}

.test {
  animation: test;
  animation-timeline: view();
}
```

Output: 

```css
@keyframes test {
  to {
    opacity: 1;
  }
}

.test {
  animation-timeline: view();
  animation: test;
}
```
