### ISSUE TITLE
bug: css-declaration-sorter orders `column-gap` above `gap`

### ISSUE THREAD

**Issue by ludofischer** [Siilwyn/css-declaration-sorter#380]
Save this style in `input.css`:
```css
.card {
   gap: 0;
   column-gap: 10px;
   row-gap: 15px;
}
```
Install `postcss`, `css-declaration-sorter` and `postcss-cli`.
Run
`postcss input.css --use css-declaration-sorter | cat`
The result is:
```css
.card {
   column-gap: 10px;
   gap: 0;
   row-gap: 15px;
}
```
which is wrong because `gap` now overrides ` column-gap`. Instead `css-declaration-sorter` should preserve the order of `gap` and `column-gap`.
