### ISSUE TITLE
`src` and `font-display` properties missing

### ISSUE THREAD

**Issue by Unknow-max** [Siilwyn/css-declaration-sorter#83]
Hi, 
I notice that the `src` property and `font-display` is missing in the smacss order (I haven't controlled other sortings).

Take, for example this code:

```css

@font-face {
  font-family: "Acumin-pro";
  src: url("../../fonts/acumin-pro/acumin-pro-bold.woff2") format("woff2"), url("../../fonts/acumin-pro/acumin-pro-bold.woff") format("woff"), url("../../fonts/acumin-pro/acumin-pro-bold.ttf") format("truetype");
  font-style: normal;
  font-weight: 800;
  font-display: fallback;
}

```

it will be after sortering :

```css
/* Acumin Pro */
@font-face {
  src: url("../../fonts/acumin-pro/acumin-pro-bold.woff2") format("woff2"), url("../../fonts/acumin-pro/acumin-pro-bold.woff") format("woff"), url("../../fonts/acumin-pro/acumin-pro-bold.ttf") format("truetype");
  font-display: fallback;
  font-family: "Acumin-pro";
  font-style: normal;
  font-weight: 800;
}
```

Not the best as you can see.
You can add those missing properties to the sort order?
Thank you very much
