### ISSUE TITLE
Properties after @include sass don't be sorted

### ISSUE THREAD

**Issue by Unknow-max** [Siilwyn/css-declaration-sorter#84]
Hi! Once again me 😅

Take this piece of code as example (I use smacss as sort order): 

```css
.circle-bg {
  padding: 1rem;
  border-radius: 50%;
  background-color: color(primary);
  @include max-size(36rem, 34.5rem);
  height: 84.2vw;
}
```
The result will be after sortering:
```css
.circle-bg {
  padding: 1rem;
  border-radius: 50%;
  background-color: color(primary);
  @include max-size(36rem, 34.5rem);
  height: 84.2vw;
}
```
Note that height isn't sortered, very strange.
But after removing @include max-height...
Before:
```scss

.circle-bg {
  padding: 1rem;
  border-radius: 50%;
  background-color: color(primary);
  height: 84.2vw;
}
```

Results:
```scss

.circle-bg {
  height: 84.2vw;
  padding: 1rem;
  border-radius: 50%;
  background-color: color(primary);
}
```
In this case, all work fine.
This is my configuration:
```javascript
// to simplify I removed importing, ecc
 return src(file, {
            base: './'
          })
          .pipe(postCss([cssDeclarationSorter({
            order: 'smacss'
          })], {
            syntax: postCssScss
          }))
          .pipe(dest('./'));
```
